on: push

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - run: echo "TESTING"
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v4
      - run: node app.js